### ISSUE TITLE
Add --strict for specific codes

### ISSUE THREAD

**Issue by natefaubion** [natefaubion/purescript-psa#14]

**Comment by hdgarrood** [comment]
Potentially a simpler first step towards this &mdash; do you think it would make sense to change the behaviour of `--strict` so that it only applies to warnings which would still appear after applying all the `--censor-X` and `--filter-X` flags? That is more along the lines of what I would have expected `--strict` to do, and also a nice thing about it is that it probably doesn't require changing the command line API as drastically as adding `--strict` for specific codes would?

**Comment by natefaubion** [comment]
Yes, this makes sense, it should definitely only raise an error for warnings that have gotten past the filters.

**Comment by natefaubion** [comment]
I've fixed this behavior in 0.4.0.
