### ISSUE TITLE
`pulp build --stash --censor-lib` doesn't seem to work as in example: "unrecognized args"

### ISSUE THREAD

**Issue by marick** [natefaubion/purescript-psa#33]
(I suspect this is a "Problem Exists Between Keyboard And Chair" issue, but I'm stuck...)

I installed with `npm install -g purescript-psa`.  `pulp build` shows beauteous warnings. However, this line, copied from the “Usage with Pulp” section, fails:

```
685 $ pulp build --stash --censor-lib 
* Error: Unrecognised arguments: --stash, --censor-lib
```

Moreover, just using `psa`, I can’t get anything to happen:

     712 $ psa --stash
                Src   Lib   All
     Warnings   0     0     0  
     Errors     0     0     0  

… even if an immediately following `pulp build` does compile changed files.

**Comment by marick** [comment]
```
Pulp version 11.0.2
purs version 0.11.6 using /usr/local/bin/purs
```

**Comment by garyb** [comment]
I'm not sure about the latter thing, but to use it with `pulp` you need to separate `psa`'s arguments with a `--`:
``` shell
pulp build -- --stash --censor-lib
```

The explanation for that is tucked away in `pulp`'s docs, with reference to passing arguments to "the compiler", but when using `psa`, "the compiler" is `psa` rather than `purs`.

Looks like we need to update the readme example here though!

**Comment by garyb** [comment]
#34

**Comment by natefaubion** [comment]
`psa` proxies arguments to `purs compile`, so `psa --stash` is the equivalent of calling `purs compile` without any source files.

**Comment by natefaubion** [comment]
I've merged @garyb's README update, so the pulp example should be correct now.
