### ISSUE TITLE
nuke on <c> press, force recompile on <enter>

### ISSUE THREAD

**Issue by kRITZCREEK** [natefaubion/purescript-psa#5]
Sometimes it's necessary to nuke `output/`. It might be nice if that could happen on capturing a keypress in the terminal. The same goes for a forced recompile.

Inspiration for this is the `yesod devel` command which captures < enter > and recompiles.

**Comment by natefaubion** [comment]
I'm not familiar with `yesod devel`. Isn't that just a long running watch process? I think a forced recompile is a good idea, but that might belong in psc proper. It would be preferable if we didn't have to intercept psc arguments, which is what I'd have to do to nuke `output` since its configurable (we'd need a better argument parser).

Though I think forced recompiles are less of an issue once we have #1.

**Comment by hdgarrood** [comment]
`yesod devel` is a long running watch process, yes. IIRC it doesn't let you choose when to recompile, it recompiles by itself when you write to any source files (which seems like the best approach, I think). Pressing enter makes it quit. I think watching might be better left to tools like pulp or gulp.

**Comment by kRITZCREEK** [comment]
Oh I thought this was meant as a long running process. Sorry for the confusion on my side. On a sidenote: you can get yesod devel to recompile if you press return in the terminal you started it in.

**Comment by hdgarrood** [comment]
Are you sure? `yesod devel` on my machine exits when I press return in the terminal I started it in, with yesod-bin 1.14.10.
